### ISSUE TITLE
Crash in Level-1 pre-processor

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#97]
**Describe the bug**
An exception has been raised at the end of Level-1 pre-processor run. The exception was raised [here](https://github.com/pysiral/pysiral/blob/483b3b3b630c0c089c52f0717a1b7ab5ed07ec0f/pysiral/l1preproc/__init__.py#L315). The error has been raised, because at the end of the run the length of the stack was not 1. 

**Log Entry**

```
2022-09-28 11:54:16.778 | INFO     | pysiral.l1preproc         | L272   | + Process input file 12658 of 12658 (100.00%) [CS_OFFL_SIR_LRM_1B_20220531T235804_20220601T000011_E001.nc]
2022-09-28 11:54:16.923 | INFO     | pysiral.l1preproc         | L981   | - No ocean data
2022-09-28 11:54:16.924 | INFO     | pysiral.l1preproc         | L275   | - No polar ocean data for curent job -> skip file
Traceback (most recent call last):
  File "/isibhv/projects/siral/scripts/altimetry/venv/awi-production-v2p5/bin/pysiral-l1preproc.py", line 146, in <module>
    pysiral_l1preproc(job)
  File "/isibhv/projects/siral/scripts/altimetry/venv/awi-production-v2p5/bin/pysiral-l1preproc.py", line 57, in pysiral_l1preproc
    l1preproc.process_input_files(file_list)
  File "/isibhv/projects/siral/scripts/altimetry/venv/awi-production-v2p5/lib/python3.7/site-packages/pysiral/l1preproc/__init__.py", line 315, in process_input_files
    raise ValueError("something went wrong here")
ValueError: something went wrong here
```

**To Reproduce**

Arguments to `pysiral-l1preproc.py`: 

    -start 2022 05 -stop 2022 05  -l1p-settings cryosat2_pds_ipf1e_v1p1

pysiral version: 483b3b3b630c0c089c52f0717a1b7ab5ed07ec0f

**Comment by shendric** [comment]
From the logfile it seems that the stack was empty, because the last file did not include any polar ocean data. This would let `len(l1_connected_stack) != 1` return False.

**Comment by shendric** [comment]
Issue has been resolved
